language: node_js
node_js:
  - "0.10"
notifications:
  recipients:
    - jari@holderdeord.no
  hipchat:
    rooms:
      secure: "dPDcvtGQXXzdj31ftZkRShrn+l1TCnTEPTdr6YVAfzAI1Ashzhr4yGvnNfMs\n4lbxYDJfRxpTO5Xd1Hte5HH7c0ijoHEGjajySSl43+nLeShw+CWhuxKSbmCM\nnICGbjLhNPSDTIg1QPO/AkUCF3YG6szmd3JX9XLathUrt0HOBTY="
    on_success: always
    on_failure: always
  template:
    - "%{author} | %{commit} | %{message} | %{build_url}"
