language: node_js
node_js:
  - "0.10"
notifications:
  recipients:
    - jari@holderdeord.no
  hipchat:
    rooms:
      secure: "mO1ZhQiTQqSEYIK1jDoBkXQsBZy0TD7UQ89KAHTaAMfjz76PKuTv0fr06J8Sxgir5GtxgCRPZhs+TaOZEm988NZe4JrfB/M1eC2V98+jT7p4CSaK+xPLh0zA96WTxhB0dHY2jzbU5G555nvlrCB97O+q0XpKMxbqC7DqtfBVsxw="
    on_success: always
    on_failure: always
  template:
    - "%{author} | %{commit} | %{message} | %{build_url}"
